<?php

namespace Acme\StoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
	public function findAllOrderedByName()
	{
		return $this->getEntityManager() // getEntityManager() Accede al gestore delle entità da dentro il repository!!!!! da fuori si usa getDoctrine()->getManager()
					->createQuery(
						'SELECT c FROM AcmeStoreBundle:Category c ORDER BY c.id ASC'
					)
					->getResult();
	}
}
