<?php

namespace Acme\StoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
	public function findAllOrderedByName()
	{
		return $this->getEntityManager() // getEntityManager() Accede al gestore delle entità da dentro il repository!!!!! da fuori si usa getDoctrine()->getManager()
					->createQuery(
						'SELECT p FROM AcmeStoreBundle:Product p ORDER BY p.id ASC'
					)
					->getResult();
	}
}